sonar.projectKey=demo
sonar.projectName=calculator_nativee
sonar.sources=.
sonar.host.url=http://localhost:9000

# Add this to your sonar-project.properties file in GitHub
sonar.javascript.lcov.reportPaths=coverage/lcov.info
