sonar.projectKey=demo
sonar.projectName=calculator_nativee
sonar.sources=.
sonar.host.url=http://localhost:9000

# TRICK: Point the JSON path to the XML file to prevent the "Skip/Abort"
sonar.dependencyCheck.jsonReportPath=dc-reports/dependency-check-report.xml
sonar.dependencyCheck.xmlReportPath=dc-reports/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=dc-reports/dependency-check-report.html

# Exclusions
sonar.exclusions=dc-reports/**,reports/**,**/node_modules/**,**/__tests__/**
