# Project identification
sonar.projectKey=demo
sonar.projectName=calculator_nativee
sonar.sources=.

# IMPORTANT: Tell the scanner where your local server is
sonar.host.url=http://localhost:9000

# DISABLE THE JSON CRASH
sonar.dependencyCheck.jsonReportPath=NONE

# FORCE THE XML PARSER
sonar.dependencyCheck.xmlReportPath=dc-reports/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=dc-reports/dependency-check-report.html

# Speed up the scan
sonar.exclusions=dc-reports/**,reports/**,**/node_modules/**,**/__tests__/**
